giravolt:
  active: true
  name: Generació Simulada
  mqtt_topic: balenya/Generacio-simulada

residencia:
  active: true
  name: Generació Residència
  mqtt_topic: balenya/generacio_Residencia

sala-polivalent:
  active: true
  name: Generació Sala Polivalent
  mqtt_topic: balenya/generacio_SalaPolivalent